version: '3.8'

services: 
  web:
    build: ./wind_bnb
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./wind_bnb :/usr/src/wind_bnb/
    ports: 
      - 8000:8000
    env_file: 
      - ./.env.dev



